import { informationArtworkRandom } from "../utils/getArtworkRandom.js"
import { informationArtwork } from "../utils/getArtwork.js"
import artwork from "./artwork.js"
import store from "./store.js"

const home = async (main) => {
    const figureABC = document.createElement('figure')
    const imgABC = document.createElement('img')
    imgABC.title = 'Art Bridge Chicago'
    imgABC.alt = 'Presentation image of Art Bridge Chicago.'
    figureABC.appendChild(imgABC)

    const titleABC = document.createElement('h1')
    titleABC.textContent = 'Art Bridge Chicago'

    const descriptionABC = document.createElement('p')
    descriptionABC.textContent = '"Art Bridge Chicago" allows the inquiry of artistic works and their authors, in addition to offering products for sale and tours of the Art Institute of Chicago through the official API.'

    const random = async () => {
        const randomWorksSection = document.createElement('section')
        const titleRandomWorksSection = document.createElement('h2')
        titleRandomWorksSection.textContent = 'Random artwork'

        const filterArtwork = async (information) => {

            const artwork = await information

            const filteredArtwork = {}

            filteredArtwork['id'] = artwork.id
            artwork.image_id == null ? filteredArtwork['image'] = '' : filteredArtwork['image'] = artwork.image_id
            artwork.date_display == '' || artwork.date_display == null ? filteredArtwork['year'] = 'Unknown' : filteredArtwork['year'] = artwork.date_display
            artwork.title == '' || artwork.title == null ? filteredArtwork['title'] = 'Untitled' : filteredArtwork['title'] = artwork.title
            return filteredArtwork
        }

        let filteredInformation = await filterArtwork(informationArtworkRandom())

        const elementsRandomWorksSection = (filteredInformation) => {

            randomWorksSection.innerHTML = ''

            const figureRandomArtwork = document.createElement('figure')
            const imgRandomArtwork = document.createElement('img')
            imgRandomArtwork.src = `https://www.artic.edu/iiif/2/${filteredInformation.image}/full/256,/0/default.jpg`
            imgRandomArtwork.alt = filteredInformation.title
            imgRandomArtwork.title = filteredInformation.title
            figureRandomArtwork.appendChild(imgRandomArtwork)

            figureRandomArtwork.addEventListener('click', () => {
                location.hash = `#artwork=${filteredInformation.id}`
                informationArtwork()
            })

            const dateRandomArtwork = document.createElement('p')
            dateRandomArtwork.textContent = filteredInformation.year

            const titleRandomArtwork = document.createElement('h3')
            titleRandomArtwork.textContent = filteredInformation.title

            const figureRandomButton = document.createElement('figure')
            const imgRandomButton = document.createElement('img')
            imgRandomButton.alt = 'Random button'
            imgRandomButton.title = 'Random button'
            figureRandomButton.appendChild(imgRandomButton)

            figureRandomButton.addEventListener('click', async () => {
                filteredInformation = await filterArtwork(informationArtworkRandom())
                elementsRandomWorksSection(filteredInformation)
            })

            randomWorksSection.append(figureRandomArtwork, dateRandomArtwork, titleRandomArtwork, figureRandomButton)
        }

        elementsRandomWorksSection(filteredInformation)

        return randomWorksSection
    }

    const featured = async () => {

        const featuredArtworksSection = document.createElement('section')

        const titleFeaturedArtworksSection = document.createElement('h2')
        titleFeaturedArtworksSection.textContent = 'Featured Artworks'

        const descriptionFeaturedArtworksSection = document.createElement('p')
        descriptionFeaturedArtworksSection.textContent = 'Listing generated by the Art Institute of Chicago.'

        featuredArtworksSection.append(titleFeaturedArtworksSection, descriptionFeaturedArtworksSection)

        const featuredArtworks = async () => {
            try {
                const response = await fetch(`https://api.artic.edu/api/v1/artworks?fields=id`)
                const information = await response.json()
                return information.data
            } catch (error) {
                console.log(error)
            }
        }

        const listArtworks = await featuredArtworks()

        for (const work of listArtworks) {
            const information = informationArtwork(work.id)
            information.id = work.id
            information.page = '#artwork'
            artwork(featuredArtworksSection, information)
        }

        return featuredArtworksSection
    }

    const preShop = async () => {
        const preShopSection = document.createElement('section')

        store(preShopSection, true)

        return preShopSection
    }

    main.append(figureABC, titleABC, descriptionABC, await random(), await featured(), await preShop())
}

export default home